HOOK_FILENAME=$(basename "$SELECTED_USERNAME")
HOOK_PATH="$SELECTED_USERNAME/hooks/use$HOOK_FILENAME.ts"
HOOK_BOILERPLATE=$(<example/useExample.ts)
HOOK_CODE=${HOOK_BOILERPLATE//REPLACE/$SELECTED_USERNAME}