TEST_HOOK_FILENAME=$(basename "$SELECTED_USERNAME")
TEST_HOOK_PATH=$SELECTED_USERNAME/hooks/use$TEST_HOOK_FILENAME.test.ts
TEST_HOOK_BOILERPLATE=$(<$SCRIPTPATH/example/useExample.test.ts)
TEST_HOOK_CODE=${TEST_HOOK_BOILERPLATE//REPLACE/$SELECTED_USERNAME}